version: '3.7'

services:
  instigo-database:
    image: postgres:12.2
    container_name: udemyTutorial
    hostname: udemyTest
    restart: always
    ports:
      - '60000:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
